# E-Mail for Certificate-Request
email: ""

# The GroupName here is used to identify your company or business unit that
# created this webhook.
# For example, this may be "acme.mycompany.com".
# This name will need to be referenced in each Issuer's `webhook` stanza to
# inform cert-manager of where to send ChallengePayload resources in order to
# solve the DNS01 challenge.
# This group name should be **unique**, hence using your own company's domain
# here is recommended.
otcdnsGroupName: ""

# The otc iam endpoint
authURL: ""

# The region for the otc iam endpoint
region: ""
